### ISSUE TITLE
error during install on Chromebook 

### ISSUE THREAD

**Issue by meepawe** [tsirysndr/crosup#73]
" install.sh: line 85: /usr/local/bin/crosup: cannot execute binary file: Exec format error "

**Comment by tsirysndr** [comment]
Hi @meepawe ,

Thank you for bringing this to my attention. The error message "cannot execute binary file: Exec format error" suggests that there might be a compatibility issue with the CPU architecture.

Currently, the binary you are trying to run is built for x86_64 architecture, and it may not be compatible with ARM architecture. This could be the reason for the error you're encountering.

Can you do an `uname -m` to check your CPU architecture ?

I'll also add support for ARM cpus.

I appreciate your understanding, and if you have any further questions or need assistance, please feel free to ask.
